[ApiCompat Task] Review undocumented behavior
southworkscom/SOUTHWORKS-azure-pipelines-tasks pull request #31
Opened 2022-08-03 11:44 UTC by erquirogasw

## Description
This PR updates the ApiCompat documentation by explaining the unexpected behavior when there are companion assemblies in the implementation folder.

## Specific Changes
- Added Unexpected Behavior section.

2022-08-03 12:38 UTC, ceciliaavila requested changes

2022-08-03 12:38 UTC, ceciliaavila commented on Tasks/ApiCompat/readme.md
> +#### Unexpected behavior
I think we should have this title at the same level as `Basic Example` or `More Information`
```suggestion
## Unexpected Behavior
```

2022-08-04 12:00 UTC, ceciliaavila requested changes

2022-08-04 12:00 UTC, ceciliaavila commented on Tasks/ApiCompat/readme.md
> +For example, having the **Microsoft.PowerFx.Core.dll* and *Microsoft.PowerFx.Transport.Attributes.dll* in the implementation folder compared against the *PowerFx.Core.dll* in the contracts folder, wi
There's an extra * here.
```suggestion
For example, having the *Microsoft.PowerFx.Core.dll* and *Microsoft.PowerFx.Transport.Attributes.dll* in the implementation folder compared against the *PowerFx.Core.dll* in the contracts folder, will result in the following error: "*CannotChangeAttribute : Attribute...changed from '[TransportTypeAttribute(0, true, null, null, false)]' in the contract to '[TransportTypeAttribute(TransportKind.ByValue, true, null, null, false)]' in the implementation.*"
```

2022-08-04 13:04 UTC, erquirogasw commented on Tasks/ApiCompat/readme.md
> +For example, having the **Microsoft.PowerFx.Core.dll* and *Microsoft.PowerFx.Transport.Attributes.dll* in the implementation folder compared against the *PowerFx.Core.dll* in the contracts folder, wi
Done. Thanks!

2022-08-04 13:05 UTC, ceciliaavila approved these changes

2022-08-04 19:34 UTC, merged